name: Build & Release

run-name: "Build and Publish Release for '${{ github.ref_name }}'"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    tags:
      - "v*.*.*" # semantic version tags

jobs:
  build-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # to create the GitHub Release

    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # actions/checkout@v6

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          TAG=${GITHUB_REF_NAME}
          gh release create "${TAG}" \
            --title "${TAG}" \
            --generate-notes
